import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.posts.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div>
            {!user.isSignedIn ? (
              <>
                <h1> Not logged in </h1>
                <SignInButton />
              </>
            ) : (
              <>
                <h1> Logged in as {user.user?.firstName} </h1>
                <SignOutButton />
              </>
            )}
          </div>
          <div>
            {data?.map((post) => (
              <div key={post.id}>
                <p>{post.authorId}</p>
                <p>{post.content}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
