name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  DATABASE_URL: "https://validDummyUrl.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: TypeScript checking
        run: npm run typecheck

      - name: Linting
        run: npm run lint
